with open('res/qml/Button.qml', 'w', encoding='utf-8') as f:
    f.write('import QtQuick 2\n')
    f.write('import QtQuick.Controls 2\n')
    f.write('import "Theme"\n\n')
    f.write('AbstractButton {\n')
    f.write('    id: root\n\n')
    f.write('    property color activeColor: Theme.primaryCyan\n')
    f.write('    property color activeBackgroundColor: Theme.panelGraphite\n')
    f.write('    property color normalBackgroundColor: Theme.deepGraphite\n')
    f.write('    property color pressedBackgroundColor: Theme.strongBorder\n')
    f.write('    property bool highlight: false\n')
    f.write('    property color normalColor: Theme.primaryText\n')
    f.write('    property color pressedColor: Theme.brightCyan\n')
    f.write('    property var icon: null\n')
    f.write('    property int cornerRadius: 2\n')
    f.write('    property int borderWidth: 1\n\n')
    f.write('    implicitHeight: 30\n')
    f.write('    implicitWidth: 56\n\n')
    f.write('    background: Rectangle {\n')
    f.write('        id: backgroundImage\n')
    f.write('        anchors.fill: parent\n')
    f.write('        color: root.normalBackgroundColor\n')
    f.write('        radius: root.cornerRadius\n')
    f.write('        border.color: root.highlight || root.checked ? Theme.primaryCyan : Theme.softBorder\n')
    f.write('        border.width: root.highlight || root.checked ? 2 : root.borderWidth\n')
    f.write('    }\n')
    f.write('    contentItem: Item {\n')
    f.write('        anchors.fill: parent\n\n')
    f.write('        Label {\n')
    f.write('            id: label\n')
    f.write('            anchors.fill: parent\n')
    f.write('            color: root.highlight || root.checked ? Theme.backgroundColor : root.normalColor\n')
    f.write('            font.bold: true\n')
    f.write('            font.capitalization: Font.AllUppercase\n')
    f.write('            font.family: Theme.fontFamily\n')
    f.write('            font.pixelSize: 10\n')
    f.write('            horizontalAlignment: Text.AlignHCenter\n')
    f.write('            text: root.text\n')
    f.write('            verticalAlignment: Text.AlignVCenter\n')
    f.write('            visible: root.text != null && root.text !== "" && (root.icon === null || root.icon.source === "")\n')
    f.write('        }\n')
    f.write('        Image {\n')
    f.write('            id: image\n')
    f.write('            anchors.centerIn: parent\n')
    f.write('            asynchronous: true\n')
    f.write('            fillMode: Image.PreserveAspectFit\n')
    f.write('            height: root.icon && root.icon.height ? root.icon.height : 20\n')
    f.write('            source: root.icon && root.icon.source ? root.icon.source : ""\n')
    f.write('            visible: root.icon && root.icon.source != ""\n')
    f.write('            width: root.icon && root.icon.width ? root.icon.width : 20\n')
    f.write('            opacity: root.enabled ? 1.0 : 0.5\n')
    f.write('        }\n')
    f.write('    }\n')
    f.write('    states: [\n')
    f.write('        State {\n')
    f.write('            name: "pressed"\n')
    f.write('            when: root.pressed\n\n')
    f.write('            PropertyChanges {\n')
    f.write('                color: root.pressedBackgroundColor\n')
    f.write('                target: backgroundImage\n')
    f.write('            }\n')
    f.write('            PropertyChanges {\n')
    f.write('                color: root.pressedColor\n')
    f.write('                target: label\n')
    f.write('            }\n')
    f.write('        },\n')
    f.write('        State {\n')
    f.write('            name: "active"\n')
    f.write('            when: (root.highlight || root.checked) && !root.pressed\n\n')
    f.write('            PropertyChanges {\n')
    f.write('                color: root.activeBackgroundColor\n')
    f.write('                target: backgroundImage\n')
    f.write('            }\n')
    f.write('            PropertyChanges {\n')
    f.write('                color: Theme.backgroundColor\n')
    f.write('                target: label\n')
    f.write('            }\n')
    f.write('        },\n')
    f.write('        State {\n')
    f.write('            name: "inactive"\n')
    f.write('            when: !root.checked && !root.highlight && !root.pressed\n\n')
    f.write('            PropertyChanges {\n')
    f.write('                color: root.normalColor\n')
    f.write('                target: label\n')
    f.write('            }\n')
    f.write('        }\n')
    f.write('    ]\n')
    f.write('}\n')

print('Done')