pragma Singleton
import QtQuick 2.12

QtObject {
    property color accentColor: "#00DFFF"
    property color backgroundColor: "#0A0E14"
    property color blue: "#00D9FF"
    property color bpmSliderBarColor: blue
    property color buttonActiveColor: white
    property color buttonDisableColor: lightGray
    property int buttonFontPixelSize: 10
    property color buttonNormalColor: midGray
    property color crossfaderBarColor: blue
    property color crossfaderOrientationColor: lightGray
    property color darkGray: "#06090E"
    property color darkGray2: "#141B24"
    property color darkGray3: "#242E3A"
    property color darkGray4: "#0E141C"
    property color deckActiveColor: "#F4FAFF"
    property color deckBackgroundColor: "#090E15"
    property color deckBeatjumpBackgroundColor: "#18222D"
    property color deckBeatjumpLabelColor: "#738395"
    property color deckEmptyCoverArt: "#1E2935"
    property color deckInfoBarBackgroundColor: '#0A1018'
    property color deckLineColor: "#1E2B37"
    property color deckLoopBackgroundColor: "#1A2632"
    property color deckLoopLabelColor: "#8190A2"
    property color deckTextColor: "#C7D4E0"
    property color effectColor: "#B86BFF"
    property color effectUnitColor: "#FF4F7B"
    property color embeddedBackgroundColor: "#B00A1018"
    property color eqFxColor: "#FF4F7B"
    property color eqHighColor: "#EAF6FF"
    property color eqLowColor: "#EAF6FF"
    property color eqMidColor: "#EAF6FF"
    property string fontFamily: "Open Sans"
    property color gainKnobColor: "#00D9FF"
    property color green: "#42E6A4"
    property string imgBpmSliderBackground: "images/slider_bpm.svg"
    property string imgButton: "images/button.svg"
    property string imgButtonPressed: "images/button_pressed.svg"
    property string imgCrossfaderBackground: "images/slider_crossfader.svg"
    property string imgCrossfaderHandle: "images/slider_handle_crossfader.svg"
    property string imgKnob: "images/knob.svg"
    property string imgKnobMini: "images/miniknob.svg"
    property string imgKnobMiniShadow: "images/miniknob_shadow.svg"
    property string imgKnobShadow: "images/knob_shadow.svg"
    property string imgMicDuckingSlider: "images/slider_micducking.svg"
    property string imgMicDuckingSliderHandle: "images/slider_handle_micducking.svg"
    property string imgPopupBackground: imgButton
    property string imgSectionBackground: "images/section.svg"
    property string imgSliderHandle: "images/slider_handle.svg"
    property string imgVolumeSliderBackground: "images/slider_volume.svg"
    property color knobBackgroundColor: "#101822"
    property color libraryPanelSplitterBackground: "#0B1118"
    property color libraryPanelSplitterHandle: "#435568"
    property color libraryPanelSplitterHandleActive: "#00D9FF"
    property color lightGray: "#758698"
    property color lightGray2: "#C2CFDB"
    property color lightGray3: "#91A1B2"
    property color midGray: "#4E6072"
    property color midGray2: "#536578"
    property color midGray3: "#3B4B5D"
    property color panelSplitterBackground: "#090E15"
    property color panelSplitterHandle: "#405468"
    property color panelSplitterHandleActive: "#00D9FF"
    property color pflActiveButtonColor: "#00D9FF"
    property color red: "#FF3B63"
    property color samplerColor: "#B86BFF"
    property color sunkenBackgroundColor: "#05080D"
    property color textColor: "#D6E1EB"
    property int textFontPixelSize: 14
    property color toolbarActiveColor: "#F4FAFF"
    property color toolbarBackgroundColor: "#111821"
    property color buttonNormalBackgroundColor: "#111922"
    property color buttonActiveBackgroundColor: "#153C49"
    property color buttonBorderColor: "#263746"
    property color buttonActiveBorderColor: "#00D9FF"
    property color buttonPressedBorderColor: "#F4FAFF"
    property color buttonControlNormalBackgroundColor: "#0F1720"
    property color volumeSliderBarColor: "#00D9FF"
    property color warningColor: "#7E3247"
    property color waveformBeatColor: "#6B7D8F"
    property color waveformCursorColor: "#FFFFFF"
    property color waveformMarkerDefault: '#FFB13B'
    property color waveformMarkerIntroOutroColor: '#7A6CFF'
    property color waveformMarkerLabel: Qt.rgba(255, 255, 255, 0.8)
    property color waveformMarkerLoopColor: '#42E6A4'
    property color waveformMarkerLoopColorDisabled: '#FFFFFF'
    property color waveformPostrollColor: midGray
    property color waveformPrerollColor: midGray
    property color white: "#F4FAFF"
    property color yellow: "#FFC857"
}
